# Use root/example as user/password credentials
version: '3.8'

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: base
      MYSQL_USER: base
      MYSQL_PASSWORD: base_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
